# Generated by Django 3.1.3 on 2020-11-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dangbaichinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('quan', models.CharField(max_length=10)),
                ('tp', models.CharField(max_length=50)),
                ('chutro', models.BooleanField(default=False)),
                ('sdt', models.IntegerField()),
                ('id_ct', models.IntegerField(default=True)),
                ('id_ntt', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='dangbaichutro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pics/')),
                ('diachi', models.CharField(max_length=100)),
                ('tieude', models.CharField(max_length=50)),
                ('noidung', models.TextField()),
                ('gia', models.IntegerField()),
                ('ngaythang', models.DateTimeField(auto_now_add=True)),
                ('id_dbc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dangbainguoitimtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('tieude', models.CharField(max_length=50)),
                ('noidung', models.TextField(max_length=255)),
                ('ngaythang', models.DateTimeField(auto_now_add=True)),
                ('id_dbc', models.IntegerField()),
            ],
        ),
    ]
