# Generated by Django 3.1.3 on 2020-12-15 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dangbaichinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('id_ct', models.IntegerField(default=True)),
                ('id_ntt', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='dangbaichutro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pics/')),
                ('diachi', models.CharField(max_length=100)),
                ('tieude', models.CharField(max_length=50)),
                ('noidung', models.TextField()),
                ('gia', models.IntegerField()),
                ('sdt', models.IntegerField()),
                ('quan', models.IntegerField()),
                ('tp', models.IntegerField()),
                ('status', models.IntegerField()),
                ('ngaythang', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='dangbainguoitimtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('tieude', models.CharField(max_length=50)),
                ('noidung', models.TextField(max_length=255)),
                ('sdt', models.IntegerField()),
                ('quan', models.IntegerField()),
                ('tp', models.IntegerField()),
                ('status', models.IntegerField()),
                ('ngaythang', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='thanhpho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='quan_tp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quan', models.CharField(max_length=50)),
                ('id_tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.thanhpho')),
            ],
        ),
    ]
