# Generated by Django 3.1.3 on 2020-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dattro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten_dp', models.CharField(max_length=150)),
                ('sdt_dp', models.IntegerField()),
                ('mail_dp', models.CharField(max_length=150)),
            ],
        ),
    ]
