# Generated by Django 3.1.3 on 2020-11-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangbainguoitimtro',
            name='id_dbc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dangbaichinh'),
        ),
    ]
