# Generated by Django 3.1.3 on 2020-11-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201118_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangbaichinh',
            name='chutro',
        ),
        migrations.RemoveField(
            model_name='dangbaichinh',
            name='sdt',
        ),
        migrations.AddField(
            model_name='dangbaichutro',
            name='sdt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dangbainguoitimtro',
            name='sdt',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
