# Generated by Django 3.1.3 on 2020-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_index', '0002_destination_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='ngaythang',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
