# Generated by Django 3.1.3 on 2020-11-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_index', '0003_auto_20201110_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='username',
            new_name='first_name',
        ),
    ]
