# Generated by Django 3.1.3 on 2020-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_index', '0004_auto_20201110_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='diachi',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='sdt',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
