# Generated by Django 3.1.3 on 2020-11-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_index', '0005_auto_20201110_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Quan',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='diachi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='luachon',
            field=models.BooleanField(default=True),
        ),
    ]
