# Generated by Django 3.1.3 on 2020-11-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_index', '0006_auto_20201110_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Quan',
            new_name='quan',
        ),
        migrations.AlterField(
            model_name='destination',
            name='luachon',
            field=models.BooleanField(default=0),
        ),
    ]
